<a href="https://colab.research.google.com/github/nevil120/Pytorch/blob/main/00_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
random_tensor_1 = torch.rand(size=(7, 7))
random_tensor_1

tensor([[0.6606, 0.8220, 0.3775, 0.0021, 0.1897, 0.7226, 0.8055],
        [0.0988, 0.0345, 0.0334, 0.9822, 0.1996, 0.4990, 0.4531],
        [0.1448, 0.6629, 0.2768, 0.7158, 0.1279, 0.5074, 0.1255],
        [0.7425, 0.1547, 0.9872, 0.2698, 0.9450, 0.0045, 0.7499],
        [0.1595, 0.9490, 0.8439, 0.7348, 0.1810, 0.3228, 0.9957],
        [0.4829, 0.1756, 0.2491, 0.6329, 0.4394, 0.6591, 0.0463],
        [0.2689, 0.1980, 0.1299, 0.8454, 0.8975, 0.0268, 0.9650]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
random_tensor_2 = torch.rand(size=(1, 7))
random_tensor_2

# Perform matrix multiplication
random_tensor_1 @ random_tensor_2.T

tensor([[0.9793],
        [0.7114],
        [1.0048],
        [1.0924],
        [1.5838],
        [0.7342],
        [1.1295]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor_1 = torch.rand(size=(7, 7))
random_tensor_2 = torch.rand(size=(1, 7))

# Matrix multiply tensors
random_tensor_1 @ random_tensor_2.T

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
if torch.cuda.is_available():
  torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
  device ='cuda'
elif torch.backends.mps.is_available():
  device = 'mps'
else:
  device = 'cpu'
print(f'Device: {device}')

# Create two random tensors on GPU
random_tensor_3 = torch.rand(size=(2, 3)).to(device)
random_tensor_4 = torch.rand(size=(2, 3)).to(device)

random_tensor_3, random_tensor_4

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul
output_tensor = random_tensor_3 @ random_tensor_4.T
output_tensor, output_tensor.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print(output_tensor.max())

# Find min
print(output_tensor.min())

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(output_tensor.argmax())

# Find arg min
print(output_tensor.argmin())

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
squeezed_random_tensor = torch.squeeze(random_tensor)

# Print out tensors and their shapes
print(random_tensor, random_tensor.shape)
print(squeezed_random_tensor, squeezed_random_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
