# PyTorch Basics Exercises

### 1. Perform standard imports
Import torch and NumPy

In [1]:
import torch
import numpy as np

### 2. Set the random seed for NumPy and PyTorch both to "42"
This allows us to share the same "random" results.

In [2]:
np.random.seed(42)
torch.manual_seed(42)

### 3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive)

In [3]:
np.random.seed(42)
arr = np.random.randint(0, 5, 6)
arr

array([3, 4, 2, 4, 4, 1])

### 4. Create a tensor "x" from the array above

In [6]:
x = torch.from_numpy(arr)
x, x.type()

(tensor([3, 4, 2, 4, 4, 1]), 'torch.LongTensor')

### 5. Change the dtype of x from 'int64' to 'int32'

In [11]:
x = x.type(torch.int32)
x, x.type()

(tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32), 'torch.IntTensor')

### 6. Reshape x into a 3x2 tensor
There are several ways to do this.

In [17]:
x = x.reshape(3, 2)
x

tensor([[3, 4],
        [2, 4],
        [4, 1]], dtype=torch.int32)

### 7. Return the right-hand column of tensor x

In [18]:
x[:, 1:]

tensor([[4],
        [4],
        [1]], dtype=torch.int32)

### 8. Without changing x, return a tensor of square values of x
There are several ways to do this.

In [19]:
x.pow(2)

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]], dtype=torch.int32)

### 9. Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive).<br>
Think about what shape it should have to permit matrix multiplication.

In [22]:
torch.manual_seed(42)
y = torch.arange(6).reshape(2, 3)
y = y.type(torch.int32)
y

tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32)

### 10. Find the matrix product of x and y

In [23]:
x @ y

tensor([[12, 19, 26],
        [12, 18, 24],
        [ 3,  8, 13]], dtype=torch.int32)